### ISSUE TITLE
Seed Icons display not match with Class Name

### ISSUE THREAD

**Issue by watchanonwcn** [SeedThemes/seed#4]
Seed-Icons ใน Seed 2.0.7 ไม่ตรงกับชื่อ class ครับ
เช่น si-clock ไปดึงไอคอน user มาแสดง

![image](https://user-images.githubusercontent.com/26668781/64129364-cd796280-cde5-11e9-8e0a-3dc3dd933a44.png)

**Comment by MennStudio** [comment]
น่าจะติดแคชนะคร้าบ 
กับต้องโหลดจากหน้าสมาชิกนะครับ ไฟล์ฟอนต์จะมีการเปลี่ยนแปลงครับ (เพราะตอนนี้ไอคอนเยอะขึ้นแล้ว)

เช็คที่ไฟล์ seed-icons.woff2 ต้องมีขนาด 11 K นะครับ?

<img width="628" alt="Screenshot 2019-09-03 11 15 04" src="https://user-images.githubusercontent.com/4017086/64143866-1825c980-ce3c-11e9-8992-efc780264cc8.png">

**Comment by watchanonwcn** [comment]
> น่าจะติดแคชนะคร้าบ
> กับต้องโหลดจากหน้าสมาชิกนะครับ ไฟล์ฟอนต์จะมีการเปลี่ยนแปลงครับ (เพราะตอนนี้ไอคอนเยอะขึ้นแล้ว)
> 
> เช็คที่ไฟล์ seed-icons.woff2 ต้องมีขนาด 11 K นะครับ?
> 
> <img alt="Screenshot 2019-09-03 11 15 04" width="628" src="https://user-images.githubusercontent.com/4017086/64143866-1825c980-ce3c-11e9-8992-efc780264cc8.png">

ลืมเคลียร์แคชจริงๆ ด้วยแหะ ขอบคุณค้าบบ
