### ISSUE TITLE
Error call to undefined function get_field() need ACF Plugin

### ISSUE THREAD

**Issue by ex0ample** [SeedThemes/seed#5]
https://github.com/SeedThemes/seed/blob/597259b2aa4a849ae7f3cef74507cc0d3dd07769/template-parts/content-headline.php#L21-L34

**Comment by MennStudio** [comment]
โอ้ว ขอบคุณมากเลยครับ เช็คไว้ด้านบน แต่ดันหลุด้านล่าง T T
